# Generated by Django 4.2.11 on 2024-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasa', models.FloatField()),
                ('montoMax', models.IntegerField()),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.CharField(max_length=500)),
                ('requisitos', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Extracupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasa', models.FloatField()),
                ('montoMax', models.IntegerField()),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.CharField(max_length=500)),
                ('requisitos', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=100)),
                ('typeCredit', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('cuotas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('document', models.IntegerField()),
                ('type', models.CharField(choices=[('VT', 'Ventanilla'), ('NM', 'Nomina')], max_length=20)),
                ('time', models.CharField(choices=[('Entre 0 y 2 años', 'Entre 0 y 2 años'), ('Entre 2 y 5 años', 'Entre 2 y 5 años'), ('Mayor a 5 años', 'Mayor a 5 años')], max_length=20)),
            ],
        ),
    ]
