# Generated by Django 4.2.11 on 2024-06-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tasa', models.FloatField()),
                ('montoMax', models.IntegerField()),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Extracupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tasa', models.FloatField()),
                ('montoMax', models.IntegerField()),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=2000)),
                ('requisitos', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=100)),
                ('typeCredit', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('cuotas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rango1', models.CharField(max_length=200)),
                ('rango2', models.CharField(max_length=200)),
                ('rango3', models.CharField(max_length=200)),
                ('rango4', models.CharField(max_length=200)),
                ('rango5', models.CharField(max_length=200)),
                ('rango6', models.CharField(max_length=200)),
                ('rango7', models.CharField(max_length=200)),
                ('rango8', models.CharField(max_length=200)),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialesRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rango1', models.CharField(max_length=200)),
                ('rango2', models.CharField(max_length=200)),
                ('rango3', models.CharField(max_length=200)),
                ('rango4', models.CharField(max_length=200)),
                ('rango5', models.CharField(max_length=200)),
                ('rango6', models.CharField(max_length=200)),
                ('rango7', models.CharField(max_length=200)),
                ('aportesMax', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scoreMin', models.IntegerField()),
                ('scoreMax', models.IntegerField()),
                ('fianza', models.FloatField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.TextField(max_length=500)),
                ('tasa', models.FloatField()),
            ],
        ),
    ]
