# Generated by Django 4.2.11 on 2024-06-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociales',
            name='rango4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociales',
            name='rango5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociales',
            name='rango6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociales',
            name='rango7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociales',
            name='rango8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
