# Generated by Django 4.2.11 on 2024-06-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_alter_tasas_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeudaAporte',
        ),
        migrations.DeleteModel(
            name='Extracupo',
        ),
        migrations.AddField(
            model_name='tasas',
            name='requsitos',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
