# Generated by Django 4.2.11 on 2024-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_delete_deudaaporte_delete_extracupo_tasas_requsitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasas',
            name='garantia',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
